export const lightTheme = {
  body: "#f6f6f7",
  text: "#161616",
  elementBackgroundColor: "#fff",
  background: "#f6f6f7",
  buttonBackground: "#bedbb0",
  buttonText: "#161616",
  buttonBackgroundHover: "#9dc888",
  buttonBackgroundActive: "#9dc888",
  buttonBackgroundFocus: "#9dc888",
  inputBackground: "#FFF",
  inputText: "#161616",
  inputBoxShadow: "0 4px 16px 0 rgba(22, 22, 22, 0.08)",
  headerBackground: "#fcfcfc",
  headerText: "#161616",
  sidebarBtn: "#161616",
  logo: "../assets/logo-black.png",
  addColumnBackground: "#fff",
  addColumnBtnBackground: "#161616",
  addColumnBtnColor: "#fff",
};

export const darkTheme = {
  body: "#212121",
  text: "#fff",
  elementBackgroundColor: "#121212",
  background: "#333",
  buttonBackground: "#bedbb0",
  buttonText: "#161616",
  buttonBackgroundHover: "#9dc888",
  buttonBackgroundActive: "#9dc888",
  buttonBackgroundFocus: "#9dc888",
  inputBackground: "#1f1f1f",
  inputText: "#fff",
  inputBoxShadow: "0 4px 16px 0 rgba(22, 22, 22, 0.08)",
  headerBackground: "#161616",
  headerText: "#fff",
  sidebarBtn: "#fff",
  logo: "/src/assets/logo-white.png",
  addColumnBackground: "#121212",
  addColumnBtnBackground: "#fff",
  addColumnBtnColor: "#000",
};

export const violetTheme = {
  body: "#d6d8ff",
  text: "#161616",
  elementBackgroundColor: "#fff",
  background: "#282c34",
  buttonBackground: "#5255bc",
  buttonText: "#FFF",
  buttonBackgroundHover: "#7b7ede",
  buttonBackgroundActive: "#7b7ede",
  buttonBackgroundFocus: "#7b7ede",
  inputBackground: "#4527a0",
  inputText: "#FFF",
  inputBoxShadow: "0 4px 16px 0 rgba(22, 22, 22, 0.08)",
  headerBackground: "#fff",
  headerText: "#fff",
  sidebarBtn: "#4527a0",
  logo: "/src/assets/logo-purple.png",
  addColumnBackground: "#fff",
  addColumnBtnBackground: "#5255bc",
  addColumnBtnColor: "#fff",
};
